load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "installer",
    srcs = ["installer.go"],
    importpath = "github.com/tweag/credential-helper/cmd/installer",
    visibility = ["//visibility:public"],
    deps = ["//agent/locate"],
)

go_test(
    name = "installer_test",
    srcs = ["installer_test.go"],
    embed = [":installer"],
)

filegroup(
    name = "all_files",
    srcs = glob(["*"]),
    visibility = ["//:__subpackages__"],
)
