load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "googlesecretmanager",
    srcs = ["googlesecretmanager.go"],
    importpath = "github.com/tweag/credential-helper/authenticate/googlesecretmanager",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "@org_golang_x_oauth2//:oauth2",
        "@org_golang_x_oauth2//google",
    ],
)

filegroup(
    name = "all_files",
    srcs = glob(["*"]),
    visibility = ["//:__subpackages__"],
)
