#!/usr/bin/env bash
# TODO: support platforms other than Linux

helper_bin=${HOME}/.cache/crendential-helper/bin/credential-helper
if [ ! -f $helper_bin ]; then
    echo "credential helper is not installed. You can install it using the following command:"
    echo "  bazel run @credential-helper//installer"
    exit 1
fi

exec "${helper_bin}" "$@"
