#!/usr/bin/env bash
# TODO: support platforms other than Linux

# You can add hardcoded configuration here or use environment variables when running Bazel
# export CREDENTIAL_HELPER_STANDALONE=1|0
#   If set to 1, the credential helper will run in standalone mode, which means it will not
#   start or connect to the agent process.
# export CREDENTIAL_HELPER_BIN=/path/to/credential-helper
#   Path to the credential helper binary. If not set, the helper will be searched in
#   ${HOME}/.cache/tweag-credential-helper/bin/credential-helper
# export CREDENTIAL_HELPER_AGENT_SOCKET=/path/to/agent.sock
#   Path of the agent socket. If not set, the helper will use the default path
#   ${HOME}/.cache/tweag-credential-helper/run/agent.sock
# export CREDENTIAL_HELPER_AGENT_PID=/path/to/agent.pid
#   Path of the agent pid file. If not set, the helper will use the default path
#   ${HOME}/.cache/tweag-credential-helper/run/agent.pid
# export CREDENTIAL_HELPER_LOGGING=off|basic|debug
#   The log level of the credential helper. Debug may expose sensitive information. Default is off.

if [ -n "${CREDENTIAL_HELPER_BIN}" ]; then
    helper_bin="${CREDENTIAL_HELPER_BIN}"
else
    helper_bin=${HOME}/.cache/tweag-credential-helper/bin/credential-helper
fi

if [ ! -f $helper_bin ]; then
    echo "credential helper is not installed. You can install it using the following command:"
    echo "  bazel run @tweag-credential-helper//installer"
    exit 1
fi

exec "${helper_bin}" "$@"
