#!/usr/bin/env bash
# TODO: support platforms other than Linux

# You can add hardcoded configuration here or use environment variables when running Bazel
# export CREDENTIAL_HELPER_STANDALONE=1|0
#   If set to 1, the credential helper will run in standalone mode, which means it will not
#   start or connect to the agent process.
# export CREDENTIAL_HELPER_INSTALL_BASE=/path/to/install_base
#  Path to the directory where the credential helper binary and state (including socket and PID file)
#  are stored. If unset, the install base is caclulated based on the user's cache dir and the md5 sum
#  of the current working directory.
# export CREDENTIAL_HELPER_BIN=/path/to/credential-helper
#   Path to the credential helper binary. If not set, the helper will be searched in
#   ${HOME}/.cache/tweag-credential-helper/bin/credential-helper
# export CREDENTIAL_HELPER_AGENT_SOCKET=/path/to/agent.sock
#   Path of the agent socket. If not set, the helper will use the default path
#   ${HOME}/.cache/tweag-credential-helper/run/agent.sock
# export CREDENTIAL_HELPER_AGENT_PID=/path/to/agent.pid
#   Path of the agent pid file. If not set, the helper will use the default path
#   ${HOME}/.cache/tweag-credential-helper/run/agent.pid
# export CREDENTIAL_HELPER_LOGGING=off|basic|debug
#   The log level of the credential helper. Debug may expose sensitive information. Default is off.

credential_helper_install_command="bazel run @tweag-credential-helper//installer"

if [ -n "${CREDENTIAL_HELPER_INSTALL_BASE}" ]; then
    install_base="${CREDENTIAL_HELPER_INSTALL_BASE}"
else
    # Bazel spawns the credential helper process using the workspace root as working directory.
    # We abuse this fact to obtain a stable, workspace specific install dir (just like Bazel's output base).
    install_base=("$(echo -n $(pwd) | md5sum)")
    install_base="${HOME}/.cache/tweag-credential-helper/${install_base}"
fi

if [ -n "${CREDENTIAL_HELPER_BIN}" ]; then
    helper_bin="${CREDENTIAL_HELPER_BIN}"
else
    helper_bin=${install_base}/bin/credential-helper
fi

if [ ! -f $helper_bin ]; then
    echo "credential helper is not installed under ${helper_bin}"
    echo "You can install it using the following command:"
    echo "  ${credential_helper_install_command}"
    exit 1
fi

exec "${helper_bin}" "$@"
